package com.example.techfix;
import android.Manifest; import android.content.pm.PackageManager; import android.net.Uri; import android.os.*; import android.widget.*; import androidx.activity.result.ActivityResultLauncher; import androidx.activity.result.contract.ActivityResultContracts; import androidx.appcompat.app.AppCompatActivity; import androidx.core.content.ContextCompat; import androidx.core.content.FileProvider; import com.example.techfix.data.AppDatabase; import com.example.techfix.data.entity.*; import java.io.File; import java.text.SimpleDateFormat; import java.util.*; import java.util.concurrent.*;
public class AppointmentDetailActivity extends AppCompatActivity {private AppDatabase db;private int appointmentId;private double servicePrice;private Uri currentPhotoUri;private final ExecutorService executor=Executors.newSingleThreadExecutor();private final Handler main=new Handler(Looper.getMainLooper());private ActivityResultLauncher<String> cameraPermissionLauncher;private ActivityResultLauncher<Uri> takePictureLauncher;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_appointment_detail);db=AppDatabase.getDatabase(getApplicationContext());appointmentId=getIntent().getIntExtra("APPOINTMENT_ID",-1);cameraPermissionLauncher=registerForActivityResult(new ActivityResultContracts.RequestPermission(),granted->{if(granted)launchCamera();else Toast.makeText(this,"Camera permission is required",Toast.LENGTH_LONG).show();});takePictureLauncher=registerForActivityResult(new ActivityResultContracts.TakePicture(),success->{if(success&&currentPhotoUri!=null){((ImageView)findViewById(R.id.ivRepairPhoto)).setImageURI(currentPhotoUri);executor.execute(()->db.appointmentDao().updateImage(appointmentId,currentPhotoUri.toString()));Toast.makeText(this,"Photo attached",Toast.LENGTH_SHORT).show();}});loadAppointmentDetails();findViewById(R.id.btnTakePhoto).setOnClickListener(v->checkCameraPermissionAndLaunch());findViewById(R.id.btnPayNow).setOnClickListener(v->processPayment());}
 private void loadAppointmentDetails(){executor.execute(()->{Appointment a=db.appointmentDao().getAppointmentById(appointmentId);if(a==null)return;Branch br=db.branchDao().getBranchById(a.getBranchId());RepairService s=db.repairServiceDao().getServiceById(a.getServiceId());servicePrice=s==null?0:s.getPrice();Payment p=db.paymentDao().getPaymentByAppointment(appointmentId);main.post(()->{((TextView)findViewById(R.id.tvDetailService)).setText(s==null?"Service":s.getName());((TextView)findViewById(R.id.tvDetailBranch)).setText(br==null?"Branch":br.getName());((TextView)findViewById(R.id.tvDetailDate)).setText(a.getRequestedDate());((TextView)findViewById(R.id.tvDetailStatus)).setText(a.getStatus());if(a.getImageUri()!=null)((ImageView)findViewById(R.id.ivRepairPhoto)).setImageURI(Uri.parse(a.getImageUri()));TextView ps=findViewById(R.id.tvPaymentStatus);Button pay=findViewById(R.id.btnPayNow);if(p!=null&&"Paid".equals(p.getStatus())){ps.setText("Paid on "+p.getPaymentDate()+" via "+p.getMethod());pay.setEnabled(false);pay.setText("Already Paid");}else ps.setText(String.format("Rs. %.2f — Not Paid",servicePrice));});});}
 private void checkCameraPermissionAndLaunch(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)launchCamera();else cameraPermissionLauncher.launch(Manifest.permission.CAMERA);}
 private void launchCamera(){try{File f=File.createTempFile("repair_"+appointmentId+"_",".jpg",getExternalFilesDir("Pictures"));currentPhotoUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);takePictureLauncher.launch(currentPhotoUri);}catch(Exception e){Toast.makeText(this,"Unable to create photo file",Toast.LENGTH_SHORT).show();}}
 private void processPayment(){executor.execute(()->{Payment existing=db.paymentDao().getPaymentByAppointment(appointmentId);String today=new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(new Date());if(existing==null)db.paymentDao().insertPayment(new Payment(appointmentId,servicePrice,"Paid",today,"Cash"));else db.paymentDao().markAsPaid(existing.getPaymentId(),"Paid",today);main.post(()->{Toast.makeText(this,"Payment successful!",Toast.LENGTH_SHORT).show();loadAppointmentDetails();});});}
 @Override protected void onDestroy(){executor.shutdown();super.onDestroy();}}
